name: 'Public Schema'
scope:
  - 'sites.*:read'
  - 'sites.17b8e90a-bb07-4ebb-b17a-e9897728cdc8:read' # EN
  - 'sites.69ae9356-f1fd-4bbc-8239-816ba3795819:read' # DE
  - 'sites.b667ce1c-4e81-4f47-be8f-f9117f42fd21:read' # ES
  - 'sections.*:read'
  - 'sections.16b5d140-0ec8-4bf0-8263-d71b291e7165:read' # Home
  - 'sections.8e7ca482-4acf-4c99-a2d2-2604a8bcb88d:read' # News
  - 'sections.d0db7657-a129-40bd-b00d-7710cf9f3dc3:read' # News Overview
  - 'usergroups.*:read'
  - 'usergroups.admin:read'
  - 'volumes.*:read'
  - 'volumes.31f620da-7617-49ed-be03-9ff85694c893:read' # Images
  - 'addresses.*:read'
