color: null
fieldLayouts:
  e649d7a2-ba3c-4fe9-a89f-6887ced68078:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-07T20:19:03+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 613e3fb4-ca6e-40cb-81f9-dfb72e3f0484 # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37de2a41-399a-4168-83fb-b9c15619da34
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-11-07T16:41:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 49e9100f-d9e4-4289-88ec-d8711b06ef1a # Headline Tag
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d5becbd-6782-4c7c-b333-0f3e009dca41
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: cb1b257e-4e3c-4b1e-a480-df09b07fbe22
        userCondition: null
handle: block_headline
hasTitleField: false
icon: null
name: 'Block: Headline'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
