color: null
fieldLayouts:
  8f9d2a56-44d8-4c79-9bbe-a999e07528aa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-22T17:20:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Headline
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 808c26ae-d495-481f-a8e6-3eb0bd7e1b62
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-02-22T17:23:11+00:00'
            elementCondition: null
            fieldUid: 4080139d-238b-4990-9747-dc47d0e284e8 # Select News
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58f2f8b3-6a61-4bf8-8d95-d3617fac9901
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 47c6e5d9-d36c-48c8-a632-4b23497c8912
        userCondition: null
handle: block_relatedNews
hasTitleField: true
icon: null
name: 'Block: Related News'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
