color: null
fieldLayouts:
  adb26259-aa13-4ade-b9e9-d423196e51e9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-07T16:40:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 613e3fb4-ca6e-40cb-81f9-dfb72e3f0484 # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 156ec57c-8e05-4add-9226-687607ff28d1
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-02-15T14:20:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 06dcc65a-0360-492d-885c-8cf26a455f95 # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79b5d9e4-0c54-4fa5-989b-ee086597651e
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-07T16:39:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 03765a14-8035-4d3a-bada-9ec41b6f99e5 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34a577ab-a40d-4fdf-b455-5ccb218984f7
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: c70b0b64-a33c-4b6d-99f0-2df664bfa1b4
        userCondition: null
handle: block_imageText
hasTitleField: false
icon: null
name: 'Block: Image Text'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
