color: null
fieldLayouts:
  6d72afc6-5a3e-47f9-a73e-c4708cecedbe:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-15T14:35:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 06dcc65a-0360-492d-885c-8cf26a455f95 # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e5547dc-29e5-4843-b0cd-b2389d4e593f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 99ea892a-b4ed-4347-89bf-c0d408174b52
        userCondition: null
handle: block_richText
hasTitleField: false
icon: null
name: 'Block: Rich Text'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
