color: null
fieldLayouts:
  d58fd658-c73c-4698-8391-95f39ccfc467:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-08T14:44:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f58e1976-da02-4678-93be-a8def53fbc4e # Select Users
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c522d613-d12d-4e17-ba79-8f2d47ddfc05
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 9033fae6-572b-452f-ba3b-3f81ae69fc26
        userCondition: null
handle: block_author
hasTitleField: false
icon: null
name: 'Block: Author'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
