color: null
fieldLayouts:
  65848ce2-bbf3-4af3-b1a3-296367ea1d1f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-07T16:36:36+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 52245e95-24a0-4570-b987-3bcf2b41e4ca
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-07T16:38:23+00:00'
            elementCondition: null
            heading: Hero
            type: craft\fieldlayoutelements\Heading
            uid: ac8b9ac7-a1d8-493a-8083-e3b7134593fb
            userCondition: null
          -
            dateAdded: '2025-02-22T17:24:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 613e3fb4-ca6e-40cb-81f9-dfb72e3f0484 # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa16e327-e972-4a11-afd2-50ecd0d9231d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-02-22T17:24:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 06dcc65a-0360-492d-885c-8cf26a455f95 # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: 'Intro Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 367eb360-1fae-4994-8326-52e8cddcc997
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-07T16:38:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 03765a14-8035-4d3a-bada-9ec41b6f99e5 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d124e445-a80b-469a-9b1f-2bd24c407c20
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-07T16:42:57+00:00'
            elementCondition: null
            heading: Content
            type: craft\fieldlayoutelements\Heading
            uid: 29292a79-5156-436d-ae2b-de676b154b75
            userCondition: null
          -
            dateAdded: '2024-11-07T16:42:57+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 677c0116-c363-4e74-b5ab-87aaeaaf261d # Content Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4fd9b77-7397-4ecd-b45b-0a09ea22433d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-22T17:24:30+00:00'
            elementCondition: null
            heading: 'Related News'
            type: craft\fieldlayoutelements\Heading
            uid: 281f8f8e-dd87-42e9-ae61-dbf99c4db028
            userCondition: null
          -
            dateAdded: '2025-02-22T17:24:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9b46253b-8924-4cb2-95b5-731480436ecc # Related News
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7922325-fa0d-4c93-ab81-d3b6fbef2b47
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f95fce80-0aae-4f8c-8cac-d8bb5eadbcde
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-23T17:37:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f65c8ce7-d94d-40d3-b234-a7504ef26035 # SEO Settings
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c27e6947-3b6b-472f-8034-a50e092e0db6
            userCondition: null
            warning: null
            width: 100
        name: 'SEO Settings'
        uid: 6afbbfaf-de16-4284-b2d6-858fd3f4a24d
        userCondition: null
handle: entry_default
hasTitleField: true
icon: null
name: 'Entry: Default'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
