color: null
fieldLayouts:
  18f457b7-c2bd-4371-804f-e621fad18fdc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-23T17:16:09+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d8a7d827-401c-4aa6-8fac-d6dcd5059dd9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-23T17:18:51+00:00'
            elementCondition: null
            heading: Hero
            type: craft\fieldlayoutelements\Heading
            uid: 16f8b157-c2e8-48a9-a0c7-69e85e538e92
            userCondition: null
          -
            dateAdded: '2025-02-23T17:18:51+00:00'
            elementCondition: null
            fieldUid: 613e3fb4-ca6e-40cb-81f9-dfb72e3f0484 # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 081fd48e-79c2-4705-8e30-722b264b7e33
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-02-23T17:18:51+00:00'
            elementCondition: null
            fieldUid: 06dcc65a-0360-492d-885c-8cf26a455f95 # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 051c38f5-0d00-401c-833e-fcc06663645c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-02-23T17:18:51+00:00'
            elementCondition: null
            fieldUid: 03765a14-8035-4d3a-bada-9ec41b6f99e5 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb5c2c7e-05ce-4772-92f3-ac058d2033ab
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-23T17:18:51+00:00'
            elementCondition: null
            heading: Content
            type: craft\fieldlayoutelements\Heading
            uid: 7a77b2ca-ffc7-4495-8843-d3310571af5e
            userCondition: null
          -
            dateAdded: '2025-02-23T17:18:51+00:00'
            elementCondition: null
            fieldUid: 677c0116-c363-4e74-b5ab-87aaeaaf261d # Content Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05a84f4c-bebd-4d63-b681-000084867d0d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 938eeac1-da2d-426c-9f09-9f2200d121d0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-23T17:38:02+00:00'
            elementCondition: null
            fieldUid: f65c8ce7-d94d-40d3-b234-a7504ef26035 # SEO Settings
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ccfdf2a8-1dfe-42cc-b219-2bb05289d762
            userCondition: null
            warning: null
            width: 100
        name: 'SEO Settings'
        uid: 30fc5102-6458-4709-9b15-d38546dd297f
        userCondition: null
handle: entry_news
hasTitleField: true
icon: null
name: 'Entry: News'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
