columnSuffix: null
handle: caption
instructions: null
name: Caption
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 56ac54ae-5bb8-4d51-9e2a-940afa549231 # Simple
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: 80
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
