columnSuffix: null
handle: selectNews
instructions: null
name: 'Select News'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: 3
  minRelations: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: false
  sources:
    - 'section:8e7ca482-4acf-4c99-a2d2-2604a8bcb88d' # News
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: language
type: craft\fields\Entries
