defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 27541a86-a923-489e-a772-e7081c0ec88a # Entry: Default
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - ''
propagationMethod: all
siteSettings:
  17b8e90a-bb07-4ebb-b17a-e9897728cdc8: # EN
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
  69ae9356-f1fd-4bbc-8239-816ba3795819: # DE
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
  b667ce1c-4e81-4f47-be8f-f9117f42fd21: # ES
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
