defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: e64eddb0-9d09-4592-a721-e22c9a10c8db # Entry: News Overview
handle: newsOverview
maxAuthors: 1
name: 'News Overview'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - ''
propagationMethod: all
siteSettings:
  17b8e90a-bb07-4ebb-b17a-e9897728cdc8: # EN
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: news
  69ae9356-f1fd-4bbc-8239-816ba3795819: # DE
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: news
  b667ce1c-4e81-4f47-be8f-f9117f42fd21: # ES
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: news
type: single
